/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leximir;

import helper.GridHelper;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import leximir.delas.menu.*;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import util.Utils;

/**
 *
 * @author rojo
 */
public final class EditorLadl extends javax.swing.JFrame {
    private DefaultTableModel tableModel ;
    /**
     * Creates new form EditorLadl
     */
    public EditorLadl() {
        try {
            initComponents();
            this.setTitle("Editor for LADL Delas Dictionaries");
            tableModel = GridHelper.getOpenEditor();
            JTable table = new JTable(getTableModel());
            RowSorter<TableModel> sort = new TableRowSorter<>(table.getModel());
            this.getjTable1().setRowSorter(sort);
            this.getjTable1().setModel(table.getModel());
        } catch (IOException ex) {
            Logger.getLogger(EditorLadl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldLemma = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldFst = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonAll = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuNew = new javax.swing.JMenu();
        jMenuItemInsertBefore = new javax.swing.JMenuItem();
        jMenuItemInsertAfter = new javax.swing.JMenuItem();
        jMenuBefore = new javax.swing.JMenu();
        jMenuAfter = new javax.swing.JMenu();
        jMenuEdit = new javax.swing.JMenu();
        jMenuView = new javax.swing.JMenu();
        jMenuSort = new javax.swing.JMenu();
        jMenuDelete = new javax.swing.JMenu();
        jMenuInflect = new javax.swing.JMenu();
        jMenuStatistics = new javax.swing.JMenu();
        jMenuWorldNet = new javax.swing.JMenu();
        jMenuSave = new javax.swing.JMenu();
        jMenuConv = new javax.swing.JMenu();
        jMenuCount = new javax.swing.JMenu();
        jMenuSaveLMF = new javax.swing.JMenu();
        jMenuHepl = new javax.swing.JMenu();
        jMenuExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("POS");

        jLabel1.setText("Lemma");

        jLabel3.setText("FST");

        jLabel4.setText("SimSem");

        jButton1.setText("1");

        jButton2.setText("2");

        jButtonAll.setText("All");

        jLabel5.setText("Lemma Inverted");

        jCheckBox1.setText("Extract Match");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel6.setText("NewDicId");

        jButton3.setText("Move");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldPos, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldLemma, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldFst, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAll)))
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox1))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addComponent(jLabel6))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLemma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButtonAll)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }

        )
    );
    jScrollPane1.setViewportView(jTable1);

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addComponent(jScrollPane1)
            .addContainerGap())
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(15, Short.MAX_VALUE))
    );

    jLabel7.setText("Search : ");

    jButtonSearch.setText("Search");
    jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonSearchActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButtonSearch)
            .addContainerGap(42, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel7)
                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonSearch))
            .addContainerGap(33, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(282, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(23, 23, 23)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(45, 45, 45))
    );

    jMenuNew.setText("New");
    jMenuNew.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jMenuNewMouseClicked(evt);
        }
    });

    jMenuItemInsertBefore.setText("insert before");
    jMenuItemInsertBefore.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemInsertBeforeActionPerformed(evt);
        }
    });
    jMenuNew.add(jMenuItemInsertBefore);

    jMenuItemInsertAfter.setText("insert after");
    jMenuItemInsertAfter.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemInsertAfterActionPerformed(evt);
        }
    });
    jMenuNew.add(jMenuItemInsertAfter);

    jMenuBar1.add(jMenuNew);

    jMenuBefore.setText("Before");
    jMenuBefore.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jMenuBeforeMouseClicked(evt);
        }
    });
    jMenuBar1.add(jMenuBefore);

    jMenuAfter.setText("After");
    jMenuAfter.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jMenuAfterMouseClicked(evt);
        }
    });
    jMenuBar1.add(jMenuAfter);

    jMenuEdit.setText("Edit");
    jMenuEdit.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jMenuEditMouseClicked(evt);
        }
    });
    jMenuBar1.add(jMenuEdit);

    jMenuView.setText("View");
    jMenuView.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jMenuViewMouseClicked(evt);
        }
    });
    jMenuBar1.add(jMenuView);

    jMenuSort.setText("Sort Dict");
    jMenuBar1.add(jMenuSort);

    jMenuDelete.setText("Delete");
    jMenuDelete.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jMenuDeleteMouseClicked(evt);
        }
    });
    jMenuBar1.add(jMenuDelete);

    jMenuInflect.setText("Inflect");
    jMenuInflect.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jMenuInflectMouseClicked(evt);
        }
    });
    jMenuBar1.add(jMenuInflect);

    jMenuStatistics.setText("Statistics");
    jMenuStatistics.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jMenuStatisticsMouseClicked(evt);
        }
    });
    jMenuStatistics.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuStatisticsActionPerformed(evt);
        }
    });
    jMenuBar1.add(jMenuStatistics);

    jMenuWorldNet.setText("WorldNet");
    jMenuBar1.add(jMenuWorldNet);

    jMenuSave.setText("Save");
    jMenuSave.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jMenuSaveMouseClicked(evt);
        }
    });
    jMenuBar1.add(jMenuSave);

    jMenuConv.setText("Conv");
    jMenuBar1.add(jMenuConv);

    jMenuCount.setText("Count WN");
    jMenuBar1.add(jMenuCount);

    jMenuSaveLMF.setText("Save LMF");
    jMenuBar1.add(jMenuSaveLMF);

    jMenuHepl.setText("Help");
    jMenuBar1.add(jMenuHepl);

    jMenuExit.setText("Exit");
    jMenuExit.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jMenuExitMouseClicked(evt);
        }
    });
    jMenuBar1.add(jMenuExit);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        try {
            String text = jTextFieldSearch.getText();
            TableRowSorter<TableModel> rowSorter;
            rowSorter = new TableRowSorter<>(GridHelper.getOpenEditorLadl().getModel());
            this.getjTable1().setRowSorter(rowSorter);
            this.getjTable1().removeAll();
            if (text.length() == 0) {
                rowSorter.setRowFilter(null);
            } else {
                //RowFilter rowFilter = RowFilter.regexFilter("(?i)" +text, 0);// recherche avec la colonne indice 0
                //rowSorter.setRowFilter(rowFilter);
                rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
            }
            this.getjTable1().repaint();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jMenuStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuStatisticsActionPerformed

    }//GEN-LAST:event_jMenuStatisticsActionPerformed

    private void jMenuNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuNewMouseClicked
        
    }//GEN-LAST:event_jMenuNewMouseClicked

    private void jMenuStatisticsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuStatisticsMouseClicked
        try {
            Map<String, HashMap<String, String>> data = new HashMap<>();
            int k = 0;
            for (int i = 0; i < this.getjTable1().getRowCount(); i++) {
                String dic = (String) this.getjTable1().getValueAt(i, 8);
                String value = (String) this.getjTable1().getValueAt(i, 0);
                if (!data.containsKey(dic)) {
                    data.put(dic, new HashMap<String,String>());
                } else {
                    if (data.get(dic).containsKey(value)) {
                        int count = Integer.parseInt(data.get(dic).get(value)) + 1;
                        data.get(dic).replace(value, String.valueOf(count));
                        k++;
                    } else {
                        k++;
                        data.get(dic).put(value, "1");
                    }
                }
            }
            Map<String, Object[]> datas = new HashMap<>();
            datas.put("1", new Object[]{"Dic", "POS", "Number"});
            int inc = 2;
            for (Map.Entry<String, HashMap<String, String>> f : data.entrySet()) {
                String key = f.getKey();
                for (Map.Entry<String, String> p : f.getValue().entrySet()) {
                    datas.put(String.valueOf(inc), new Object[]{key, p.getKey(), p.getValue()});
                    inc++;
                }
            }
            HSSFWorkbook workbook = new HSSFWorkbook();
            //String filename = Utils.getValueXml("pathExportStatistics");
            String filename = "statisticsTmp.xls";
            Utils.exportJtableToExcel(workbook, datas,filename);
            
            JOptionPane.showMessageDialog(null, "file created in \n"+filename);
        } catch (IOException ex) {
           JOptionPane.showMessageDialog(null, "Error"+ex.getMessage());
        }
    }//GEN-LAST:event_jMenuStatisticsMouseClicked

    private void jMenuDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuDeleteMouseClicked
        int dialogResult = JOptionPane.showConfirmDialog (null, "Do you want to delete this row?","Warning",JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.YES_OPTION){
            int t = this.getjTable1().getSelectedRow();
            this.getTableModel().removeRow(t);
            JOptionPane.showMessageDialog(null, "rows deleted !");
        }
        
    }//GEN-LAST:event_jMenuDeleteMouseClicked

    private void jMenuItemInsertAfterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInsertAfterActionPerformed
        if(this.getjTable1().getSelectedRow()!=-1){
            MenuAddBeforeDelas ad=new MenuAddBeforeDelas(this,this.getjTable1().getSelectedRow());
            ad.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "No selected value");
        }
    }//GEN-LAST:event_jMenuItemInsertAfterActionPerformed

    private void jMenuItemInsertBeforeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInsertBeforeActionPerformed
        if(this.getjTable1().getSelectedRow()!=-1){
            MenuAddBeforeDelas ad=new MenuAddBeforeDelas(this,this.getjTable1().getSelectedRow());
            ad.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "No selected value");
        }
    }//GEN-LAST:event_jMenuItemInsertBeforeActionPerformed

    private void jMenuViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuViewMouseClicked
        if(this.getjTable1().getSelectedRow()!=-1){
            Object [] obj =new Object[10];
            for(int i=0;i<10;i++){
                obj[i]=this.getjTable1().getModel().getValueAt(this.getjTable1().getSelectedRow(), i);
            }
            MenuViewDelas viewDelas=new MenuViewDelas(this,obj);
            viewDelas.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "No selected value");
        }
    }//GEN-LAST:event_jMenuViewMouseClicked

    private void jMenuEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuEditMouseClicked
        if(this.getjTable1().getSelectedRow()!=-1){
            Object [] obj =new Object[10];
            for(int i=0;i<10;i++){
                obj[i]=this.getjTable1().getModel().getValueAt(this.getjTable1().getSelectedRow(), i);
            }
            MenuEditDelas editDelas=new MenuEditDelas(this,obj,this.getjTable1().getSelectedRow());
            editDelas.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "No selected value");
        }
    }//GEN-LAST:event_jMenuEditMouseClicked

    private void jMenuBeforeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBeforeMouseClicked
        if(this.getjTable1().getSelectedRow()!=-1){
            Object [] obj =new Object[10];
            for(int i=0;i<10;i++){
                obj[i]=this.getjTable1().getModel().getValueAt(this.getjTable1().getSelectedRow(), i);
            }
            MenuBeforeDelas beforeDelas=new MenuBeforeDelas(this,obj,this.getjTable1().getSelectedRow());
            beforeDelas.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "No selected value");
        }
    }//GEN-LAST:event_jMenuBeforeMouseClicked

    private void jMenuAfterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAfterMouseClicked
       if(this.getjTable1().getSelectedRow()!=-1){
            Object [] obj =new Object[10];
            for(int i=0;i<10;i++){
                obj[i]=this.getjTable1().getModel().getValueAt(this.getjTable1().getSelectedRow(), i);
            }
            MenuAfterDelas afterDelas=new MenuAfterDelas(this,obj,this.getjTable1().getSelectedRow());
            afterDelas.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "No selected value");
        }
    }//GEN-LAST:event_jMenuAfterMouseClicked

    private void jMenuSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSaveMouseClicked
        int dialogResult = JOptionPane.showConfirmDialog (null, "This will overwrite your dictionaries. Are you sure?","Save Delas Dictioneries in Unicode",JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.YES_OPTION){
            BufferedWriter bfw;
            Map<String,List<String>> fileData=new HashMap<>();
            for(int row = 0; row < jTable1.getRowCount(); row ++){
                
                String file = (String) jTable1.getValueAt(row, 8);
                String lemma = (String) jTable1.getValueAt(row, 1);
                String fstCode = (String) jTable1.getValueAt(row, 3);
                String str = lemma+","+fstCode.substring(1);
                String comment =(String) jTable1.getValueAt(row, 4);
                if(comment!=null && comment.trim().length()>0){
                    str = str+"//"+jTable1.getValueAt(row, 4);
                }
                str=str+"\n";
                if(fileData.containsKey(file)){
                    fileData.get(file).add(str);
                }
                else{
                    List<String> tmp = new ArrayList<>();
                    tmp.add(str);
                    fileData.put(file, tmp);
                }
            }
            for(Map.Entry<String, List<String>> data:fileData.entrySet()){
                try {
                    //bfw = new BufferedWriter(new FileWriter(Utils.getValueXml("pathDelas")+"/"+data.getKey()));
                    bfw = new BufferedWriter(new FileWriter("/Users/rojo/Documents/LeXimir4UnitexRes/Delas/"+data.getKey()));
                    for(String lines:data.getValue()){
                        bfw.write(lines);
                    }
                    bfw.close();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "error :"+ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jMenuSaveMouseClicked

    private void jMenuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuExitMouseClicked
       this.setVisible(false);
    }//GEN-LAST:event_jMenuExitMouseClicked

    private void jMenuInflectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuInflectMouseClicked
        if(this.getjTable1().getSelectedRow()!=-1){
            BufferedWriter bfw;
            try {
                String DelasTmpName="DelasTmp.dic";
                writeInDelasTmp(DelasTmpName);
                String[] command ={
                    "//Users//rojo//Unitex-GramLab-3.1//App//UnitexToolLogger", "MultiFlex" ,
                    "DelasTmp.dic",
                    "-o","DelafTmp.dic",
                    "-a","//Users//rojo//Unitex-GramLab-3.1//French//Alphabet.txt",
                    "-d","//Users//rojo//Unitex-GramLab-3.1//French//Inflection//"
                };
                ProcessBuilder pb = new ProcessBuilder(command);
                pb.redirectOutput(ProcessBuilder.Redirect.INHERIT);
                pb.redirectError(ProcessBuilder.Redirect.INHERIT);
                pb.start();
                JOptionPane.showMessageDialog(null, "done !!");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "error :"+ex.getMessage());
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "No selected value");
        }
        
    }//GEN-LAST:event_jMenuInflectMouseClicked

    private void writeInDelasTmp(String DelasTmpName) throws IOException {
        BufferedWriter bfw;
        bfw = new BufferedWriter(new FileWriter(DelasTmpName));
        bfw.write((String) this.getjTable1().getModel().getValueAt(this.getjTable1().getSelectedRow(), 1));
        bfw.write(",");
        bfw.write((String) this.getjTable1().getModel().getValueAt(this.getjTable1().getSelectedRow(), 2));
        bfw.close();
    }

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorLadl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAll;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenuAfter;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuBefore;
    private javax.swing.JMenu jMenuConv;
    private javax.swing.JMenu jMenuCount;
    private javax.swing.JMenu jMenuDelete;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuExit;
    private javax.swing.JMenu jMenuHepl;
    private javax.swing.JMenu jMenuInflect;
    private javax.swing.JMenuItem jMenuItemInsertAfter;
    private javax.swing.JMenuItem jMenuItemInsertBefore;
    private javax.swing.JMenu jMenuNew;
    private javax.swing.JMenu jMenuSave;
    private javax.swing.JMenu jMenuSaveLMF;
    private javax.swing.JMenu jMenuSort;
    private javax.swing.JMenu jMenuStatistics;
    private javax.swing.JMenu jMenuView;
    private javax.swing.JMenu jMenuWorldNet;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldFst;
    private javax.swing.JTextField jTextFieldLemma;
    private javax.swing.JTextField jTextFieldPos;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jTable1
     */
    public javax.swing.JTable getjTable1() {
        return jTable1;
    }

    /**
     * @return the gm
     */
    public DefaultTableModel getTableModel() {
        return tableModel;
    }
}
