/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leximir;

import helper.DelasHelper;
import helper.GridHelper;
import java.awt.Color;
import java.awt.Component;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.io.StringWriter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import static leximir.delac.menu.MenuDelac.getNodeList;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;
import util.CompoundsUtils;
import util.Utils;

/**
 *
 * @author rojo
 */
public class Strategy extends javax.swing.JFrame {
private DefaultTableModel tableModel ;
    /**
     * Creates new form Strategy
     */
    public Strategy() {
        initComponents();
        DefaultTableCellRenderer color = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object valueLemaAll, boolean isSelected, boolean hasFocus, int row, int column) {
                final Component c = super.getTableCellRendererComponent(table, valueLemaAll, isSelected, hasFocus, row, column);
                c.setBackground(row % 2 == 0 ? Color.LIGHT_GRAY : Color.WHITE);
                c.setForeground(Color.black);
                return c;
            }
        };
        this.jTablePredict.setDefaultRenderer(Object.class, color);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldSearchfile = new javax.swing.JTextField();
        jButtonSearchFile = new javax.swing.JButton();
        jButtonOpenFile = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldStrategy = new javax.swing.JTextField();
        jButtonStrategySearch = new javax.swing.JButton();
        jButtonStrategyOpen = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePredict = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableDlf = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableRule = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuPrediction = new javax.swing.JMenu();
        jMenuDisambiguation = new javax.swing.JMenu();
        jMenuExport = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("File with coumpounds list "));

        jTextFieldSearchfile.setEditable(false);

        jButtonSearchFile.setText("Search");
        jButtonSearchFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchFileActionPerformed(evt);
            }
        });

        jButtonOpenFile.setText("open");
        jButtonOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldSearchfile, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSearchFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOpenFile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSearchfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearchFile)
                    .addComponent(jButtonOpenFile))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Strategy "));

        jTextFieldStrategy.setEditable(false);

        jButtonStrategySearch.setText("Search");
        jButtonStrategySearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStrategySearchActionPerformed(evt);
            }
        });

        jButtonStrategyOpen.setText("open");
        jButtonStrategyOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStrategyOpenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldStrategy, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonStrategySearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonStrategyOpen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldStrategy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonStrategySearch)
                    .addComponent(jButtonStrategyOpen))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Result selection preview"));

        jCheckBox1.setText("Coumpounds witch are not in dictionnary");

        jCheckBox2.setText("Coumpounds witch are in dictionnary");

        jCheckBox3.setText("Only first prediction for each compound");

        jCheckBox4.setText("open txt file with result");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Automatic tem extraction"));

        jLabel1.setText("CorpusId:");

        jButton5.setText("open");

        jButton6.setText("save prediction");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTablePredict.setAutoCreateRowSorter(true);
        jTablePredict.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "select", "Clema", "CFLX", "Word NO", "Predict Id", "Rule Id", "RulePart Id", "SinSem"
            }
        ));
        jTablePredict.setShowGrid(false);
        jTablePredict.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTablePredict);

        jLabel2.setText("MWU");

        jLabel3.setText("CFLX");

        jLabel4.setText("SIN2");

        jLabel5.setText("OK/NOT OK");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Result with rules detail", jPanel8);

        jTableDlf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableDlf.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTableDlf);

        jTableRule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableRule.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jTableRule);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Results", jPanel9);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenuPrediction.setText("Prediction");
        jMenuPrediction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuPredictionMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuPrediction);

        jMenuDisambiguation.setText("Disambiguation");
        jMenuBar1.add(jMenuDisambiguation);

        jMenuExport.setText("Export Result");
        jMenuBar1.add(jMenuExport);

        jMenu1.setText("dictionnary production");
        jMenuBar1.add(jMenu1);

        jMenu7.setText("exit");
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchFileActionPerformed
        JFileChooser theFileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("TEXT FILES", "txt", "text");
        theFileChooser.setFileFilter(filter);
        theFileChooser.showOpenDialog(this);
        theFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        File f = theFileChooser.getSelectedFile();
        jTextFieldSearchfile.setText(f.getAbsolutePath());
    }//GEN-LAST:event_jButtonSearchFileActionPerformed

    private void jButtonOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenFileActionPerformed
        try {
            String filename = jTextFieldSearchfile.getText();       
            Desktop.getDesktop().open(new File(filename));
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error: "+ex);
        }
    }//GEN-LAST:event_jButtonOpenFileActionPerformed

    private void jButtonStrategySearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStrategySearchActionPerformed
        JFileChooser theFileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("XML FILES", "xml");
        theFileChooser.setFileFilter(filter);
        theFileChooser.showOpenDialog(this);
        theFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        File f = theFileChooser.getSelectedFile();
        jTextFieldStrategy.setText(f.getAbsolutePath());
    }//GEN-LAST:event_jButtonStrategySearchActionPerformed

    private void jButtonStrategyOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStrategyOpenActionPerformed
       try {
            String filename = jTextFieldStrategy.getText();       
            Desktop.getDesktop().open(new File(filename));
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error: "+ex);
        }
    }//GEN-LAST:event_jButtonStrategyOpenActionPerformed

    private void jMenuPredictionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPredictionMouseClicked
        try {
            ArrayList<String> f = Utils.readFile(jTextFieldSearchfile.getText());
            List<String> result = new ArrayList<>();
            List<String> predict = new ArrayList<>();
            for(String words:f){
                int indexLema = words.indexOf("+");
                String Clema = words.substring(0,indexLema-1);
                String[] wordSplit = Clema.split("-|\\ ");
                char separator = 0;
                int separatorSpace = Clema.indexOf(" ");
                int separatorIndex = Clema.indexOf("-");
                String flxGroup = "AC_2XA";

                if (separatorSpace > -1) {
                    separator = Clema.charAt(separatorSpace);
                } else if (separatorIndex > -1) {
                    separator = Clema.charAt(separatorIndex);
                }
                result.addAll(CompoundsUtils.getDlfInFile(Clema));
                jTableDlf.setModel(GridHelper.getDataforjTableDlf(result));
                jTableDlf.repaint();
                
                
                 /**
                 * *** complete datatableRule **
                 */
                Object[][] getAllDelas = DelasHelper.getAllDelasFromDicToObject();
                Object[][] allDelasImportant = new Object[jTableDlf.getRowCount()][6];
                int indexImportantDelas = 0;
                for (Object[] allDela : getAllDelas) {

                    for (int i=0;i<jTableDlf.getRowCount();i++) {
                        String text = (String) jTableDlf.getModel().getValueAt(i, 1);
                        String compare = (String) allDela[1];
                        try {
                            if (text.equals(compare)) {
                                String word = (String) jTableDlf.getModel().getValueAt(i, 0);
                                word = word.split(",")[0];
                                allDelasImportant[indexImportantDelas][0] = 1;// Rule

                                allDelasImportant[indexImportantDelas][1] = allDela[1];// Lema
                                allDelasImportant[indexImportantDelas][2] = allDela[2];// FLX CODE
                                allDelasImportant[indexImportantDelas][3] = jTableDlf.getModel().getValueAt(i, 3);// GramCat
                                allDelasImportant[indexImportantDelas][4] = allDela[0];// POS
                                allDelasImportant[indexImportantDelas][5] = word;// words
                                indexImportantDelas++;
                            }
                        } catch (java.lang.NullPointerException e) {
                            continue;
                        }
                    }
                }
                String[] enteteRule = {"Rule", "Lema", "FLX", "GramCat", "POS", "words"};
                jTableRule.setModel((new JTable(new DefaultTableModel(allDelasImportant, enteteRule))).getModel());
                jTableRule.repaint();
                
                String[] PosWords = new String[wordSplit.length];
                Set<String> pos = new HashSet();
                for (int j = 0; j < wordSplit.length; j++) {
                    for (int k = 0; k < jTableDlf.getRowCount(); k++) {
                        if (jTableDlf.getValueAt(k, 0) != null) {
                            int indexLemajTableDlf = ((String) jTableDlf.getValueAt(k, 0)).indexOf(",");
                            String lema = ((String) jTableDlf.getValueAt(k, 0)).substring(0, indexLemajTableDlf);
                            if (lema.equals(wordSplit[j])) {
                                pos.add((String) jTableDlf.getValueAt(k, 2));
                            }
                        }
                    }
                    String w = "";
                    for (String s : pos) {
                        w = s + ",";
                    }
                    PosWords[j] = "".equals(w) ? w : w.substring(0, w.length() - 1);
                }
                
                predict.addAll(getLemaFromXmlRule(wordSplit, separator, flxGroup, PosWords));

                jTablePredict.setModel(GridHelper.getDataforjTablePredict(predict));
                jTablePredict.repaint();
            }
            
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error: "+ex);
        } catch (ParserConfigurationException ex) {
        Logger.getLogger(Strategy.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SAXException ex) {
        Logger.getLogger(Strategy.class.getName()).log(Level.SEVERE, null, ex);
    } catch (TransformerException ex) {
        Logger.getLogger(Strategy.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jMenuPredictionMouseClicked
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Strategy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Strategy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Strategy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Strategy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Strategy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonOpenFile;
    private javax.swing.JButton jButtonSearchFile;
    private javax.swing.JButton jButtonStrategyOpen;
    private javax.swing.JButton jButtonStrategySearch;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDisambiguation;
    private javax.swing.JMenu jMenuExport;
    private javax.swing.JMenu jMenuPrediction;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableDlf;
    private javax.swing.JTable jTablePredict;
    private javax.swing.JTable jTableRule;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextFieldSearchfile;
    private javax.swing.JTextField jTextFieldStrategy;
    // End of variables declaration//GEN-END:variables

    private List<String> getLemaFromXmlRule(String[] words, char separator, String flxGroup, String[] POSwords) throws ParserConfigurationException, SAXException, IOException, TransformerException {
        boolean ruleIdFound = false;
        boolean flxFound = false;
        String flx = new String();
        String ruleNo = "";
        NodeList nList = getNodeList();
        String returns = "";
        List<String> ret = new ArrayList<>();
        for (int temp = 0; temp < nList.getLength(); temp++) {
            Node nNode = nList.item(temp);
            if (nNode.getNodeType() == Node.ELEMENT_NODE) {
                Element eElement = (Element) nNode;
                if (eElement.getAttribute("WordNo").equals(Integer.toString(words.length))) {
                    ruleIdFound = true;
                    NodeList ndRule = eElement.getElementsByTagName("Rule");
                    for (int i = 0; i < ndRule.getLength(); i++) {
                        Node nNodeRule = ndRule.item(i);
                        if (nNodeRule.getNodeType() == Node.ELEMENT_NODE) {
                            Element eElementRule = (Element) nNodeRule;
                            
                                flxFound = true;
                                flx = eElementRule.getAttribute("CFLX");
                                ruleNo = eElementRule.getAttribute("ID");
                                /**
                                 * **** For General Rules ****
                                 */
                                NodeList ndRuleGenCond = eElementRule.getElementsByTagName("RuleGenCond");
                                for (int j = 0; j < ndRuleGenCond.getLength(); j++) {
                                    Node nNodeRuleGenCond = ndRuleGenCond.item(j);
                                    if (nNodeRuleGenCond.getNodeType() == Node.ELEMENT_NODE) {
                                        Element eElementRuleGenCond = (Element) nNodeRuleGenCond;
                                        NodeList ndWord = eElementRuleGenCond.getElementsByTagName("Word");
                                        for (int k = 0; k < ndWord.getLength(); k++) {
                                            Node nNodeWord = ndWord.item(k);
                                            if (nNodeWord.getNodeType() == Node.ELEMENT_NODE) {
                                                Element eElementWord = (Element) nNodeWord;
                                                if (eElementWord.getAttribute("POS").equals(POSwords[k]) || eElementWord.getAttribute("POS").equals("MOT")) {
                                                    if (eElementWord.getAttribute("Flex").equals("false") || eElementWord.getAttribute("Flex") == null || eElementWord.getAttribute("Flex").equals("")) {
                                                        //returns = returns+words[k]+"(flexion off)";
                                                        returns = returns + getFlexSpec(words[k]);
                                                    } else {
                                                        HashMap<String,String> condition = new HashMap<>();
                                                        if(eElementWord.getAttribute("Anim") != null)condition.put("Anim", eElementWord.getAttribute("Anim"));
                                                        if(eElementWord.getAttribute("Case") != null)condition.put("Case", eElementWord.getAttribute("Case"));
                                                        if(eElementWord.getAttribute("Num") != null)condition.put("Num", eElementWord.getAttribute("Num"));
                                                        if(eElementWord.getAttribute("Gen") != null)condition.put("Gen", eElementWord.getAttribute("Gen"));
                                                        String flex = getFlex(words[k], eElementWord.getAttribute("POS"),condition);
                                                        //returns = returns+words[k]+"(flexion on)"+flex;
                                                        returns = returns + words[k] + flex;
                                                    }
                                                } else {
                                                    //returns = returns+words[k]+"(flexion off)";
                                                    returns = returns + words[k];
                                                }
                                            }
                                            returns = returns + separator;
                                        }
                                    }
                                }
                                /**
                                 * **** End For General Rules ****
                                 */
                                ret.add(returns.substring(0, returns.length() - 1) + "," + flx + "," + ruleNo);
                                returns = "";
                            
                        }
                    }
                }
            }
        }
        if (flxFound == false) {
            throw new NullPointerException(flxGroup + " flx not found in rule " + words.length);
        }
        if (ruleIdFound == false) {
            throw new NullPointerException(words.length + " rule not found");
        }
        return ret;
    }
    public NodeList getNodeList() throws ParserConfigurationException, SAXException, IOException {
        File inputFile = new File(jTextFieldStrategy.getText());
        DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
        DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
        Document doc = dBuilder.parse(inputFile);
        doc.getDocumentElement().normalize();
        return doc.getElementsByTagName("Rules");
    }

    private String getFlex(String words, String poss,HashMap<String,String> condition) {
        String flexion = "";
        for (int k = 0; k < jTableRule.getRowCount(); k++) {
            if (jTableRule.getValueAt(k, 1) != null) {
                if (!((String) jTableRule.getValueAt(k, 5)).equals(words)) {
                    flexion = "";
                } else {
                    if (words.equals((String) jTableRule.getValueAt(k, 5)) && (poss.equals((String) jTableRule.getValueAt(k, 4)) || poss.equals("MOT"))) {//get lemma in Table
                        String lema = (String) jTableRule.getValueAt(k, 1);
                        String flex = (String) jTableRule.getValueAt(k, 2);
                        String gramcat = (String) jTableRule.getValueAt(k, 3);
                        /*String gram="";
                        if(poss=="N"){
                            if(condition.containsKey("Gen")){
                                gram = gram.concat(gramcat.substring(0, 1));
                            }
                            if(condition.containsKey("Num")){
                                String num = gramcat.substring(1, 2);
                            }
                            if(condition.containsKey("Case")){
                                String Case = gramcat.substring(2, 3);
                            }
                            if(condition.containsKey("Anim")){
                                String anime = gramcat.substring(3);
                            }
                        }
                        boolean notLetterFound=false;
                        for (char c : gramcat.toCharArray()){  // loop through string as character array
                            if (!set.contains(c)){         // if a character is not found in the set
                                notLetterfound = true;    // make notLetterFound true and break the loop
                                break;                       
                            }
                        }
                        if(gram.)*/
                        flexion = "(" + lema + "." + flex + ":" + gramcat + ")";
                        return flexion;
                    }
                }
            }
        }
        return "";
    }
    private static String nodeToString(Node node)
    throws TransformerException
    {
        StringWriter buf = new StringWriter();
        Transformer xform = TransformerFactory.newInstance().newTransformer();
        xform.setOutputProperty(OutputKeys.OMIT_XML_DECLARATION, "yes");
        xform.transform(new DOMSource(node), new StreamResult(buf));
        return(buf.toString());
    }

    private String getFlexSpec(String word) {
        return word;
    }
}
