/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leximir.delac.menu;

import helper.GridHelper;
import java.awt.Color;
import java.awt.Component;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import leximir.EditorDelac;
import model.StaticValue;
import util.Utils;

/**
 *
 * @author rojo
 */
public class MenuAddBeforeDelac extends javax.swing.JFrame {
    private EditorDelac editorDelac;
    private Object[] obj;
    private int valueSelected;
    private DefaultTableModel tableModel ;
    /**
     * Creates new form MenuAddBeforeDelac
     */
    public MenuAddBeforeDelac() {
        initComponents();
    }

    public MenuAddBeforeDelac(EditorDelac aThis, Object[] obj, int selectedRow) {
        initComponents();
        DefaultTableCellRenderer color = new DefaultTableCellRenderer()
            {
                @Override
                public Component getTableCellRendererComponent(JTable table, Object valueLemaAll, boolean isSelected, boolean hasFocus, int row, int column)
                {
                    final Component c = super.getTableCellRendererComponent(table, valueLemaAll, isSelected, hasFocus, row, column);
                    c.setBackground(row % 2 == 0 ? Color.LIGHT_GRAY : Color.WHITE);
                    c.setForeground(Color.black);
                    return c;
                }
            };
        editorDelac = aThis;
        this.obj = obj;
        this.valueSelected=selectedRow+1;
        jTextFieldPos.setText((String) this.obj[0]);
        jTextFieldCFlx.setText((String) this.obj[3]);
        jTextFieldDictionnary.setText((String) this.obj[8]);
        jTextFieldDicId.setText(String.valueOf((int) this.obj[9]));
        jTextFieldLemaId.setText(String.valueOf((int) this.obj[7])+1);
        //this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.jTable1.setDefaultRenderer(Object.class, color);
        this.jTableDelaf.setDefaultRenderer(Object.class, color);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupRules = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanelCompound = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldLemaAll = new javax.swing.JTextField();
        jTextFieldLema = new javax.swing.JTextField();
        jTextFieldComment = new javax.swing.JTextField();
        WorldNet = new javax.swing.JTextField();
        jTextFieldPos = new javax.swing.JTextField();
        jTextFieldCFlx = new javax.swing.JTextField();
        jTextFieldsynSem = new javax.swing.JTextField();
        jTextFieldDictionnary = new javax.swing.JTextField();
        jTextFieldDicId = new javax.swing.JTextField();
        jTextFieldLemaId = new javax.swing.JTextField();
        jPanelPrediction = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldClemaAll = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAddSimpleForm = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDelaf = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuSave = new javax.swing.JMenu();
        jMenuClose = new javax.swing.JMenu();
        jMenuInflect = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Lema (All)");

        jLabel3.setText("Lema");

        jLabel4.setText("Comment");

        jLabel5.setText("WorldNet");

        jLabel6.setText("POS");

        jLabel7.setText("CFlx");

        jLabel8.setText("SynSem");

        jLabel9.setText("Dictionnary");

        jLabel10.setText("DicId");

        jLabel11.setText("LemaId");

        jTextFieldLemaAll.setEditable(false);
        jTextFieldLemaAll.setBackground(new java.awt.Color(204, 204, 204));

        jTextFieldLema.setEditable(false);
        jTextFieldLema.setBackground(new java.awt.Color(204, 204, 204));

        jTextFieldPos.setEditable(false);
        jTextFieldPos.setBackground(new java.awt.Color(204, 204, 204));

        jTextFieldDictionnary.setEditable(false);
        jTextFieldDictionnary.setBackground(new java.awt.Color(204, 204, 204));

        jTextFieldDicId.setEditable(false);
        jTextFieldDicId.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanelCompoundLayout = new javax.swing.GroupLayout(jPanelCompound);
        jPanelCompound.setLayout(jPanelCompoundLayout);
        jPanelCompoundLayout.setHorizontalGroup(
            jPanelCompoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCompoundLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanelCompoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanelCompoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCompoundLayout.createSequentialGroup()
                        .addGroup(jPanelCompoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldLema)
                            .addComponent(jTextFieldComment)
                            .addComponent(WorldNet, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCompoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelCompoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCFlx)
                            .addComponent(jTextFieldsynSem)
                            .addComponent(jTextFieldPos, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextFieldLemaAll))
                .addGap(37, 37, 37)
                .addGroup(jPanelCompoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanelCompoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldDictionnary)
                    .addComponent(jTextFieldDicId)
                    .addComponent(jTextFieldLemaId, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );
        jPanelCompoundLayout.setVerticalGroup(
            jPanelCompoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCompoundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCompoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldLemaAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCompoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanelCompoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel9)
                        .addComponent(jTextFieldLema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldDictionnary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelCompoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCFlx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDicId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCompoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(WorldNet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldsynSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLemaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Compound", jPanelCompound);

        jLabel1.setText("Coumpound for prediction of CLemaAll and  CFlx :");

        buttonGroupRules.add(jRadioButton1);
        jRadioButton1.setText("First rule strategy");

        buttonGroupRules.add(jRadioButton2);
        jRadioButton2.setText("Second rule strategy");

        javax.swing.GroupLayout jPanelPredictionLayout = new javax.swing.GroupLayout(jPanelPrediction);
        jPanelPrediction.setLayout(jPanelPredictionLayout);
        jPanelPredictionLayout.setHorizontalGroup(
            jPanelPredictionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPredictionLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldClemaAll, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPredictionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPredictionLayout.setVerticalGroup(
            jPanelPredictionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPredictionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPredictionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldClemaAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(jPanelPredictionLayout.createSequentialGroup()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Prediction", jPanelPrediction);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "", "", "","",""},
                {"2", "", "", "","",""},
            },
            new String [] {
                "RB", "Form", "Lema", "FST Code","GramCat","Separator"
            }
        ));
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonAddSimpleForm.setText("Add simple form");
        jButtonAddSimpleForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddSimpleFormActionPerformed(evt);
            }
        });

        jButtonRefresh.setText("Refresh Lema");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        jTableDelaf.setAutoCreateRowSorter(true);
        jScrollPane2.setViewportView(jTableDelaf);

        jLabel12.setText("Defaf<Ctrl+F> - Copy <Ctrl+C>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButtonAddSimpleForm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddSimpleForm)
                    .addComponent(jButtonRefresh)
                    .addComponent(jLabel12))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuSave.setText("Save&Close");
        jMenuSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSaveMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSave);

        jMenuClose.setText("Just close");
        jMenuClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCloseMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuClose);

        jMenuInflect.setText("Inflect");
        jMenuInflect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuInflectMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuInflect);

        jMenu4.setText("Prediction");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Dlf");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Debug file");
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Selected Rule");
        jMenuBar1.add(jMenu7);

        jMenu8.setText("FSD");
        jMenuBar1.add(jMenu8);

        jMenu9.setText("Check in Dictionnary");
        jMenuBar1.add(jMenu9);

        jMenu10.setText("WorldNet");
        jMenuBar1.add(jMenu10);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        String valueLemaAll = "";
        String valueLema = "";
        for(int row = 0; row < jTable1.getRowCount(); row ++){
            if(!jTable1.getModel().getValueAt(row, 1).equals("")){
                valueLemaAll = valueLemaAll + jTable1.getModel().getValueAt(row, 1);
                valueLema = valueLema +jTable1.getModel().getValueAt(row, 1);
                if(!jTable1.getModel().getValueAt(row, 2).equals("")){
                    valueLemaAll = valueLemaAll +"("+ jTable1.getModel().getValueAt(row, 2);
                    if(!jTable1.getModel().getValueAt(row, 3).equals("")){
                        valueLemaAll = valueLemaAll +"."+ jTable1.getModel().getValueAt(row, 3);
                        if(!jTable1.getModel().getValueAt(row, 4).equals("")){
                            valueLemaAll = valueLemaAll +":"+ jTable1.getModel().getValueAt(row, 4)+")";
                        }
                    }
                }
                if(!jTable1.getModel().getValueAt(row, 5).equals("")){
                    valueLema = valueLema +jTable1.getModel().getValueAt(row, 5);
                    valueLemaAll = valueLemaAll + jTable1.getModel().getValueAt(row, 5);
                }
                else{
                    valueLema = valueLema +" ";
                    valueLemaAll = valueLemaAll + " ";
                }
            }
        }
        jTextFieldClemaAll.setText(valueLema);
        jTextFieldLemaAll.setText(valueLemaAll);
        jTextFieldLema.setText(valueLema);
        
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jMenuSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSaveMouseClicked
       try{
            String lemmaAll = jTextFieldLemaAll.getText();
            
            String FST = jTextFieldCFlx.getText();
            String synSem = "+"+jTextFieldsynSem.getText();
            String dic = jTextFieldDictionnary.getText();
            String comment=jTextFieldComment.getText();

            Object[] row = Utils.delacToObject(lemmaAll,FST,synSem,comment,dic);
            editorDelac.getTableModel().insertRow(valueSelected,row);
            this.setVisible(false);
        }
        catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jMenuSaveMouseClicked

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        if(this.jTable1.getSelectedRow()!=-1){
            if(evt.isControlDown() && evt.getKeyCode()==KeyEvent.VK_F){
                try {
                    String value = (String) this.jTable1.getModel().getValueAt(this.jTable1.getSelectedRow(), 1);
                    String tempPath = StaticValue.delafTmpPathDelac;
                    Utils.generateDelaf(tempPath, value);
                    tableModel = GridHelper.getDelafInDelacForDelac();
                    JTable table = new JTable(tableModel);
                    this.jTableDelaf.setModel(table.getModel());
                    this.jTableDelaf.removeAll();
                    //
                    this.jTableDelaf.repaint();     
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null,ex.getMessage());
                }
            }
            if(evt.isControlDown() && evt.getKeyCode()==KeyEvent.VK_C){
                String value = (String) this.jTable1.getModel().getValueAt(this.jTable1.getSelectedRow(), 1);
                this.jTable1.getModel().setValueAt(value, this.jTable1.getSelectedRow(), 2);
            }
        }
    }//GEN-LAST:event_jTable1KeyPressed

    private void jMenuInflectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuInflectMouseClicked
        if(jTextFieldLemaAll.getText().equals("")||jTextFieldCFlx.getText().equals("")){
            JOptionPane.showMessageDialog(null,"something wrong");
        }
        else{
            try {
                String lema = jTextFieldLemaAll.getText();
                String code = jTextFieldCFlx.getText();
                Utils.InflectDelas(lema, code);
                JOptionPane.showMessageDialog(null, "done");
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "error :"+ex.getMessage());
            }catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "error :"+ex.getMessage());
            }
            
        } 
    }//GEN-LAST:event_jMenuInflectMouseClicked

    private void jButtonAddSimpleFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddSimpleFormActionPerformed
        DefaultTableModel newmodel = (DefaultTableModel) jTable1.getModel();
        newmodel.addRow(new Object[]{jTable1.getModel().getRowCount()+1,"","","","",""});
    }//GEN-LAST:event_jButtonAddSimpleFormActionPerformed

    private void jMenuCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCloseMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jMenuCloseMouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        String value = jTextFieldClemaAll.getText();
        if(!value.equals("")){
            try {
                String tempPath = StaticValue.delafTmpPathDelac;
                Utils.generateDelaf(tempPath, value);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "error :"+ex.getMessage());
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Value Clma is Empty");
        }
    }//GEN-LAST:event_jMenu4MouseClicked

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAddBeforeDelac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAddBeforeDelac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAddBeforeDelac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAddBeforeDelac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAddBeforeDelac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField WorldNet;
    private javax.swing.ButtonGroup buttonGroupRules;
    private javax.swing.JButton jButtonAddSimpleForm;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuClose;
    private javax.swing.JMenu jMenuInflect;
    private javax.swing.JMenu jMenuSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCompound;
    private javax.swing.JPanel jPanelPrediction;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableDelaf;
    private javax.swing.JTextField jTextFieldCFlx;
    private javax.swing.JTextField jTextFieldClemaAll;
    private javax.swing.JTextField jTextFieldComment;
    private javax.swing.JTextField jTextFieldDicId;
    private javax.swing.JTextField jTextFieldDictionnary;
    private javax.swing.JTextField jTextFieldLema;
    private javax.swing.JTextField jTextFieldLemaAll;
    private javax.swing.JTextField jTextFieldLemaId;
    private javax.swing.JTextField jTextFieldPos;
    private javax.swing.JTextField jTextFieldsynSem;
    // End of variables declaration//GEN-END:variables
}
